name: Python CI/CD Pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: pytest

      - name: Create Build Folder
        run: |
          mkdir build
          copy hello.py build\hello.py
          copy requirements.txt build\requirements.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-application
          path: build/

  deploy:
    needs: build
    runs-on: windows-latest
    environment: production

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v5
        with:
          name: python-application
          path: application

      - name: Deploy Application
        run: |
          echo "Deploying Application..."
          dir application
          echo "Deployment Completed"